/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedRestaurantsIndexRouteImport } from './routes/_authenticated/restaurants.index'
import { Route as AuthenticatedRestaurantsIdRouteImport } from './routes/_authenticated/restaurants.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestaurantsIndexRoute =
  AuthenticatedRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRestaurantsIdRoute =
  AuthenticatedRestaurantsIdRouteImport.update({
    id: '/restaurants/$id',
    path: '/restaurants/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
  '/restaurants/': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
  '/restaurants': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
  '/_authenticated/restaurants/': typeof AuthenticatedRestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/upload'
    | '/restaurants/$id'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/upload'
    | '/restaurants/$id'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/upload'
    | '/_authenticated/restaurants/$id'
    | '/_authenticated/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurants/': {
      id: '/_authenticated/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof AuthenticatedRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurants/$id': {
      id: '/_authenticated/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedRestaurantsIdRoute: typeof AuthenticatedRestaurantsIdRoute
  AuthenticatedRestaurantsIndexRoute: typeof AuthenticatedRestaurantsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedRestaurantsIdRoute: AuthenticatedRestaurantsIdRoute,
  AuthenticatedRestaurantsIndexRoute: AuthenticatedRestaurantsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
