
ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS zomato_id TEXT,
  ADD COLUMN IF NOT EXISTS subzone TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS restaurants_zomato_id_key
  ON public.restaurants (zomato_id) WHERE zomato_id IS NOT NULL;

ALTER TABLE public.daily_metrics RENAME COLUMN menu_to_order TO impressions_to_menu;

ALTER TABLE public.daily_metrics
  ADD COLUMN IF NOT EXISTS market_share NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS average_rating NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rated_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bad_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rejected_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS kpt_delayed_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS poor_rated_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_complaints NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lost_sales NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS online_pct NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS offline_hours NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS kpt_minutes NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS for_accuracy NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS menu_opens NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cart_builds NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS placed_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS new_user_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS repeat_user_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lapsed_user_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lunch_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dinner_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snacks_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS breakfast_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS late_night_orders NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_menu_opens NUMERIC DEFAULT 0;
